version: "3"

# includes:
#   app:
#     taskfile: packages/app/
#     dir: packages/app/
#     optional: true

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  i:
    cmds:
      - yarn

  run:
    cmds:
      - quasar dev


  ##################################################################################################

  quick:
    cmds:
      - task: commit
      - task: commit
  #      - task: pull
  #      - task: push

  commit:
    cmds:
      - git add .
      - git commit -m "update"
    ignore_error: true

  pull:
    cmds:
      - git config pull.rebase false
      - git pull origin main

  push:
    cmds:
      - git push origin dev/tauri:dev/tauri --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
